language: c
 
install:
  - sudo add-apt-repository -y ppa:directhex/monoxide 
  - sudo apt-get update
  - sudo apt-get install mono-devel mono-gmcs nunit-console
 
script:
  - mozroots --import --sync
  - wget http://nuget.org/nuget.exe
  - cd src && mono --runtime=v4.0 ./nuget.exe restore
  - xbuild WhiteSharp/WhiteSharp.csproj