init:
  - ps: iex ((new-object net.webclient).DownloadString('https://gist.githubusercontent.com/ilya-murzinov/4b782e7d5df80eebb4ae/raw/1a24f7c9cec48f5a4cd19d9641b10f33f0b4b390/Appveyor%2520RDP'))
before_build:
  - nuget restore src/WhiteSharp.sln

build_script: 
  - msbuild src/WhiteSharp.sln /p:Configuration=Debug /t:Rebuild
  
test_script:
  - nunit3-console src/WhiteSharp.Tests/bin/Debug/WhiteSharp.Tests.dll --noresult
