init:
  - ps: iex ((new-object net.webclient).DownloadString('httpshttps://gist.githubusercontent.com/ilya-murzinov/4b782e7d5df80eebb4ae/raw/9378adb4421c2f21b347d5a55a73ad0d78356eda/Appveyor%2520RDP'))
before_build:
  - nuget restore src/WhiteSharp.sln

build_script: 
  - msbuild src/WhiteSharp.sln /p:Configuration=Debug /t:Rebuild
  
test_script:
  - nunit3-console src/WhiteSharp.Tests/bin/Debug/WhiteSharp.Tests.dll --noresult
