init:
  - ps: iex ((new-object net.webclient).DownloadString('https://gist.githubusercontent.com/ilya-murzinov/4b782e7d5df80eebb4ae/raw/9ae09e01d03a9ec5ed7f90cb942a10245c4a81e3/Appveyor%2520RDP'))
before_build:
  - nuget restore src/WhiteSharp.sln

build_script: 
  - msbuild src/WhiteSharp.sln /p:Configuration=Debug /t:Rebuild
  
test_script:
  - nunit3-console src/WhiteSharp.Tests/bin/Debug/WhiteSharp.Tests.dll --noresult
